[package]
name = "lapce-lldb"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
lapce-plugin = "0.1.1"
serde_json = "1.0.59"
